#pragma once 
/* This header contains all needed OpenGL function pointers.
*/
#include "mygl_types.hpp"

#if __cpp_noexcept_function_type >= 201510
    MYGL_NOEXCEPT noexcept
#else
    MYGL_NOEXCEPT
#endif
extern void (*glActiveShaderProgram)(pipeline pipeline, shader_program program) MYGL_NOEXCEPT;
extern void (*glActiveTexture)(texture texture) MYGL_NOEXCEPT;
extern void (*glAttachShader)(shader_program program, shader shader) MYGL_NOEXCEPT;
extern void (*glBeginConditionalRender)(unsigned int id, GLenum mode) MYGL_NOEXCEPT;
extern void (*glBeginQuery)(GLenum target, query id) MYGL_NOEXCEPT;
extern void (*glBeginQueryIndexed)(GLenum target, unsigned int index, query id) MYGL_NOEXCEPT;
extern void (*glBeginTransformFeedback)(GLenum primitiveMode) MYGL_NOEXCEPT;
extern void (*glBindAttribLocation)(shader_program program, unsigned int index, const char * name) MYGL_NOEXCEPT;
extern void (*glBindBuffer)(GLenum target, buffer buffer) MYGL_NOEXCEPT;
extern void (*glBindBufferBase)(GLenum target, unsigned int index, buffer buffer) MYGL_NOEXCEPT;
extern void (*glBindBufferRange)(GLenum target, unsigned int index, buffer buffer, ptrdiff_t offset, ptrdiff_t size) MYGL_NOEXCEPT;
extern void (*glBindBuffersBase)(GLenum target, unsigned int first, int count, const buffer * buffers) MYGL_NOEXCEPT;
extern void (*glBindBuffersRange)(GLenum target, unsigned int first, int count, const buffer * buffers, const ptrdiff_t * offsets, const ptrdiff_t * sizes) MYGL_NOEXCEPT;
extern void (*glBindFragDataLocation)(shader_program program, unsigned int color, const char * name) MYGL_NOEXCEPT;
extern void (*glBindFragDataLocationIndexed)(shader_program program, unsigned int colorNumber, unsigned int index, const char * name) MYGL_NOEXCEPT;
extern void (*glBindFramebuffer)(GLenum target, framebuffer framebuffer) MYGL_NOEXCEPT;
extern void (*glBindImageTexture)(unsigned int unit, texture texture, int level, bool layered, int layer, GLenum access, GLenum format) MYGL_NOEXCEPT;
extern void (*glBindImageTextures)(unsigned int first, int count, const texture * textures) MYGL_NOEXCEPT;
extern void (*glBindProgramPipeline)(pipeline pipeline) MYGL_NOEXCEPT;
extern void (*glBindRenderbuffer)(GLenum target, renderbuffer renderbuffer) MYGL_NOEXCEPT;
extern void (*glBindSampler)(unsigned int unit, sampler sampler) MYGL_NOEXCEPT;
extern void (*glBindSamplers)(unsigned int first, int count, const sampler * samplers) MYGL_NOEXCEPT;
extern void (*glBindTexture)(GLenum target, texture texture) MYGL_NOEXCEPT;
extern void (*glBindTextureUnit)(unsigned int unit, texture texture) MYGL_NOEXCEPT;
extern void (*glBindTextures)(unsigned int first, int count, const texture * textures) MYGL_NOEXCEPT;
extern void (*glBindTransformFeedback)(GLenum target, transform_feedback id) MYGL_NOEXCEPT;
extern void (*glBindVertexArray)(vertex_array array) MYGL_NOEXCEPT;
extern void (*glBindVertexBuffer)(unsigned int bindingindex, buffer buffer, ptrdiff_t offset, int stride) MYGL_NOEXCEPT;
extern void (*glBindVertexBuffers)(unsigned int first, int count, const buffer * buffers, const ptrdiff_t * offsets, const int * strides) MYGL_NOEXCEPT;
extern void (*glBlendColor)(float red, float green, float blue, float alpha) MYGL_NOEXCEPT;
extern void (*glBlendEquation)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha) MYGL_NOEXCEPT;
extern void (*glBlendEquationSeparatei)(unsigned int buf, GLenum modeRGB, GLenum modeAlpha) MYGL_NOEXCEPT;
extern void (*glBlendEquationSeparateiARB)(unsigned int buf, GLenum modeRGB, GLenum modeAlpha) MYGL_NOEXCEPT;
extern void (*glBlendEquationi)(unsigned int buf, GLenum mode) MYGL_NOEXCEPT;
extern void (*glBlendEquationiARB)(unsigned int buf, GLenum mode) MYGL_NOEXCEPT;
extern void (*glBlendFunc)(GLenum sfactor, GLenum dfactor) MYGL_NOEXCEPT;
extern void (*glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha) MYGL_NOEXCEPT;
extern void (*glBlendFuncSeparatei)(unsigned int buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) MYGL_NOEXCEPT;
extern void (*glBlendFuncSeparateiARB)(unsigned int buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) MYGL_NOEXCEPT;
extern void (*glBlendFunci)(unsigned int buf, GLenum src, GLenum dst) MYGL_NOEXCEPT;
extern void (*glBlendFunciARB)(unsigned int buf, GLenum src, GLenum dst) MYGL_NOEXCEPT;
extern void (*glBlitFramebuffer)(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, GLbitfield mask, GLenum filter) MYGL_NOEXCEPT;
extern void (*glBlitNamedFramebuffer)(framebuffer readFramebuffer, framebuffer drawFramebuffer, int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, GLbitfield mask, GLenum filter) MYGL_NOEXCEPT;
extern void (*glBufferAddressRangeNV)(GLenum pname, unsigned int index, uint64_t address, ptrdiff_t length) MYGL_NOEXCEPT;
extern void (*glBufferData)(GLenum target, ptrdiff_t size, const void * data, GLenum usage) MYGL_NOEXCEPT;
extern void (*glBufferStorage)(GLenum target, ptrdiff_t size, const void * data, GLbitfield flags) MYGL_NOEXCEPT;
extern void (*glBufferSubData)(GLenum target, ptrdiff_t offset, ptrdiff_t size, const void * data) MYGL_NOEXCEPT;
extern void (*glCallCommandListNV)(command_list list) MYGL_NOEXCEPT;
extern GLenum(*glCheckFramebufferStatus)(GLenum target) MYGL_NOEXCEPT;
extern GLenum(*glCheckNamedFramebufferStatus)(framebuffer framebuffer, GLenum target) MYGL_NOEXCEPT;
extern void (*glClampColor)(GLenum target, GLenum clamp) MYGL_NOEXCEPT;
extern void (*glClear)(GLbitfield mask) MYGL_NOEXCEPT;
extern void (*glClearBufferData)(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void * data) MYGL_NOEXCEPT;
extern void (*glClearBufferSubData)(GLenum target, GLenum internalformat, ptrdiff_t offset, ptrdiff_t size, GLenum format, GLenum type, const void * data) MYGL_NOEXCEPT;
extern void (*glClearBufferfi)(buffer buffer, int drawbuffer, float depth, int stencil) MYGL_NOEXCEPT;
extern void (*glClearBufferfv)(buffer buffer, int drawbuffer, const float * value) MYGL_NOEXCEPT;
extern void (*glClearBufferiv)(buffer buffer, int drawbuffer, const int * value) MYGL_NOEXCEPT;
extern void (*glClearBufferuiv)(buffer buffer, int drawbuffer, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glClearColor)(float red, float green, float blue, float alpha) MYGL_NOEXCEPT;
extern void (*glClearDepth)(double depth) MYGL_NOEXCEPT;
extern void (*glClearDepthf)(float d) MYGL_NOEXCEPT;
extern void (*glClearNamedBufferData)(buffer buffer, GLenum internalformat, GLenum format, GLenum type, const void * data) MYGL_NOEXCEPT;
extern void (*glClearNamedBufferSubData)(buffer buffer, GLenum internalformat, ptrdiff_t offset, ptrdiff_t size, GLenum format, GLenum type, const void * data) MYGL_NOEXCEPT;
extern void (*glClearNamedFramebufferfi)(framebuffer framebuffer, GLenum buffer, int drawbuffer, float depth, int stencil) MYGL_NOEXCEPT;
extern void (*glClearNamedFramebufferfv)(framebuffer framebuffer, GLenum buffer, int drawbuffer, const float * value) MYGL_NOEXCEPT;
extern void (*glClearNamedFramebufferiv)(framebuffer framebuffer, GLenum buffer, int drawbuffer, const int * value) MYGL_NOEXCEPT;
extern void (*glClearNamedFramebufferuiv)(framebuffer framebuffer, GLenum buffer, int drawbuffer, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glClearStencil)(int s) MYGL_NOEXCEPT;
extern void (*glClearTexImage)(texture texture, int level, GLenum format, GLenum type, const void * data) MYGL_NOEXCEPT;
extern void (*glClearTexSubImage)(texture texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, GLenum format, GLenum type, const void * data) MYGL_NOEXCEPT;
extern GLenum(*glClientWaitSync)(GLsync sync, GLbitfield flags, uint64_t timeout) MYGL_NOEXCEPT;
extern void (*glClipControl)(GLenum origin, GLenum depth) MYGL_NOEXCEPT;
extern void (*glColorFormatNV)(int size, GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glColorMask)(bool red, bool green, bool blue, bool alpha) MYGL_NOEXCEPT;
extern void (*glColorMaski)(unsigned int index, bool r, bool g, bool b, bool a) MYGL_NOEXCEPT;
extern void (*glColorP3ui)(GLenum type, unsigned int color) MYGL_NOEXCEPT;
extern void (*glColorP3uiv)(GLenum type, const unsigned int * color) MYGL_NOEXCEPT;
extern void (*glColorP4ui)(GLenum type, unsigned int color) MYGL_NOEXCEPT;
extern void (*glColorP4uiv)(GLenum type, const unsigned int * color) MYGL_NOEXCEPT;
extern void (*glCommandListSegmentsNV)(command_list list, unsigned int segments) MYGL_NOEXCEPT;
extern void (*glCompileCommandListNV)(command_list list) MYGL_NOEXCEPT;
extern void (*glCompileShader)(shader shader) MYGL_NOEXCEPT;
extern void (*glCompressedTexImage1D)(GLenum target, int level, GLenum internalformat, int width, int border, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTexImage2D)(GLenum target, int level, GLenum internalformat, int width, int height, int border, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTexImage3D)(GLenum target, int level, GLenum internalformat, int width, int height, int depth, int border, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTexSubImage1D)(GLenum target, int level, int xoffset, int width, GLenum format, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTexSubImage2D)(GLenum target, int level, int xoffset, int yoffset, int width, int height, GLenum format, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTexSubImage3D)(GLenum target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, GLenum format, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTextureSubImage1D)(texture texture, int level, int xoffset, int width, GLenum format, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTextureSubImage2D)(texture texture, int level, int xoffset, int yoffset, int width, int height, GLenum format, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCompressedTextureSubImage3D)(texture texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, GLenum format, int imageSize, const void * data) MYGL_NOEXCEPT;
extern void (*glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, ptrdiff_t readOffset, ptrdiff_t writeOffset, ptrdiff_t size) MYGL_NOEXCEPT;
extern void (*glCopyImageSubData)(unsigned int srcName, GLenum srcTarget, int srcLevel, int srcX, int srcY, int srcZ, unsigned int dstName, GLenum dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int srcWidth, int srcHeight, int srcDepth) MYGL_NOEXCEPT;
extern void (*glCopyNamedBufferSubData)(buffer readBuffer, buffer writeBuffer, ptrdiff_t readOffset, ptrdiff_t writeOffset, ptrdiff_t size) MYGL_NOEXCEPT;
extern void (*glCopyPathNV)(path resultPath, path srcPath) MYGL_NOEXCEPT;
extern void (*glCopyTexImage1D)(GLenum target, int level, GLenum internalformat, int x, int y, int width, int border) MYGL_NOEXCEPT;
extern void (*glCopyTexImage2D)(GLenum target, int level, GLenum internalformat, int x, int y, int width, int height, int border) MYGL_NOEXCEPT;
extern void (*glCopyTexSubImage1D)(GLenum target, int level, int xoffset, int x, int y, int width) MYGL_NOEXCEPT;
extern void (*glCopyTexSubImage2D)(GLenum target, int level, int xoffset, int yoffset, int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glCopyTexSubImage3D)(GLenum target, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glCopyTextureSubImage1D)(texture texture, int level, int xoffset, int x, int y, int width) MYGL_NOEXCEPT;
extern void (*glCopyTextureSubImage2D)(texture texture, int level, int xoffset, int yoffset, int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glCopyTextureSubImage3D)(texture texture, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glCoverFillPathInstancedNV)(int numPaths, GLenum pathNameType, const void * paths, path pathBase, GLenum coverMode, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glCoverFillPathNV)(path path, GLenum coverMode) MYGL_NOEXCEPT;
extern void (*glCoverStrokePathInstancedNV)(int numPaths, GLenum pathNameType, const void * paths, path pathBase, GLenum coverMode, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glCoverStrokePathNV)(path path, GLenum coverMode) MYGL_NOEXCEPT;
extern void (*glCreateBuffers)(int n, buffer * buffers) MYGL_NOEXCEPT;
extern void (*glCreateCommandListsNV)(int n, command_list * lists) MYGL_NOEXCEPT;
extern void (*glCreateFramebuffers)(int n, framebuffer * framebuffers) MYGL_NOEXCEPT;
extern shader_program(*glCreateProgram)() MYGL_NOEXCEPT;
extern void (*glCreateProgramPipelines)(int n, pipeline * pipelines) MYGL_NOEXCEPT;
extern void (*glCreateQueries)(GLenum target, int n, query * ids) MYGL_NOEXCEPT;
extern void (*glCreateRenderbuffers)(int n, renderbuffer * renderbuffers) MYGL_NOEXCEPT;
extern void (*glCreateSamplers)(int n, sampler * samplers) MYGL_NOEXCEPT;
extern shader(*glCreateShader)(GLenum type) MYGL_NOEXCEPT;
extern shader_program(*glCreateShaderProgramv)(GLenum type, int count, const char *const* strings) MYGL_NOEXCEPT;
extern void (*glCreateStatesNV)(int n, state * states) MYGL_NOEXCEPT;
extern void (*glCreateTextures)(GLenum target, int n, texture * textures) MYGL_NOEXCEPT;
extern void (*glCreateTransformFeedbacks)(int n, transform_feedback * ids) MYGL_NOEXCEPT;
extern void (*glCreateVertexArrays)(int n, vertex_array * arrays) MYGL_NOEXCEPT;
extern void (*glCullFace)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glDebugMessageCallback)(GLDEBUGPROC callback, const void * userParam) MYGL_NOEXCEPT;
extern void (*glDebugMessageCallbackKHR)(GLDEBUGPROCKHR callback, const void * userParam) MYGL_NOEXCEPT;
extern void (*glDebugMessageControl)(GLenum source, GLenum type, GLenum severity, int count, const unsigned int * ids, bool enabled) MYGL_NOEXCEPT;
extern void (*glDebugMessageControlKHR)(GLenum source, GLenum type, GLenum severity, int count, const unsigned int * ids, bool enabled) MYGL_NOEXCEPT;
extern void (*glDebugMessageInsert)(GLenum source, GLenum type, unsigned int id, GLenum severity, int length, const char * buf) MYGL_NOEXCEPT;
extern void (*glDebugMessageInsertKHR)(GLenum source, GLenum type, unsigned int id, GLenum severity, int length, const char * buf) MYGL_NOEXCEPT;
extern void (*glDeleteBuffers)(int n, const buffer * buffers) MYGL_NOEXCEPT;
extern void (*glDeleteCommandListsNV)(int n, const command_list * lists) MYGL_NOEXCEPT;
extern void (*glDeleteFramebuffers)(int n, const framebuffer * framebuffers) MYGL_NOEXCEPT;
extern void (*glDeletePathsNV)(path path, int range) MYGL_NOEXCEPT;
extern void (*glDeleteProgram)(shader_program program) MYGL_NOEXCEPT;
extern void (*glDeleteProgramPipelines)(int n, const pipeline * pipelines) MYGL_NOEXCEPT;
extern void (*glDeleteQueries)(int n, const query * ids) MYGL_NOEXCEPT;
extern void (*glDeleteRenderbuffers)(int n, const renderbuffer * renderbuffers) MYGL_NOEXCEPT;
extern void (*glDeleteSamplers)(int count, const sampler * samplers) MYGL_NOEXCEPT;
extern void (*glDeleteShader)(shader shader) MYGL_NOEXCEPT;
extern void (*glDeleteStatesNV)(int n, const state * states) MYGL_NOEXCEPT;
extern void (*glDeleteSync)(GLsync sync) MYGL_NOEXCEPT;
extern void (*glDeleteTextures)(int n, const texture * textures) MYGL_NOEXCEPT;
extern void (*glDeleteTransformFeedbacks)(int n, const transform_feedback * ids) MYGL_NOEXCEPT;
extern void (*glDeleteVertexArrays)(int n, const vertex_array * arrays) MYGL_NOEXCEPT;
extern void (*glDepthFunc)(GLenum func) MYGL_NOEXCEPT;
extern void (*glDepthMask)(bool flag) MYGL_NOEXCEPT;
extern void (*glDepthRange)(double n, double f) MYGL_NOEXCEPT;
extern void (*glDepthRangeArrayv)(unsigned int first, int count, const double * v) MYGL_NOEXCEPT;
extern void (*glDepthRangeIndexed)(unsigned int index, double n, double f) MYGL_NOEXCEPT;
extern void (*glDepthRangef)(float n, float f) MYGL_NOEXCEPT;
extern void (*glDetachShader)(shader_program program, shader shader) MYGL_NOEXCEPT;
extern void (*glDisable)(GLenum cap) MYGL_NOEXCEPT;
extern void (*glDisableClientState)(GLenum array) MYGL_NOEXCEPT;
extern void (*glDisableVertexArrayAttrib)(vertex_array vaobj, unsigned int index) MYGL_NOEXCEPT;
extern void (*glDisableVertexAttribArray)(unsigned int index) MYGL_NOEXCEPT;
extern void (*glDisablei)(GLenum target, unsigned int index) MYGL_NOEXCEPT;
extern void (*glDispatchCompute)(unsigned int num_groups_x, unsigned int num_groups_y, unsigned int num_groups_z) MYGL_NOEXCEPT;
extern void (*glDispatchComputeGroupSizeARB)(unsigned int num_groups_x, unsigned int num_groups_y, unsigned int num_groups_z, unsigned int group_size_x, unsigned int group_size_y, unsigned int group_size_z) MYGL_NOEXCEPT;
extern void (*glDispatchComputeIndirect)(ptrdiff_t indirect) MYGL_NOEXCEPT;
extern void (*glDrawArrays)(GLenum mode, int first, int count) MYGL_NOEXCEPT;
extern void (*glDrawArraysIndirect)(GLenum mode, const void * indirect) MYGL_NOEXCEPT;
extern void (*glDrawArraysInstanced)(GLenum mode, int first, int count, int instancecount) MYGL_NOEXCEPT;
extern void (*glDrawArraysInstancedBaseInstance)(GLenum mode, int first, int count, int instancecount, unsigned int baseinstance) MYGL_NOEXCEPT;
extern void (*glDrawBuffer)(GLenum buf) MYGL_NOEXCEPT;
extern void (*glDrawBuffers)(int n, const GLenum * bufs) MYGL_NOEXCEPT;
extern void (*glDrawCommandsAddressNV)(GLenum primitiveMode, const uint64_t * indirects, const int * sizes, unsigned int count) MYGL_NOEXCEPT;
extern void (*glDrawCommandsNV)(GLenum primitiveMode, buffer buffer, const ptrdiff_t * indirects, const int * sizes, unsigned int count) MYGL_NOEXCEPT;
extern void (*glDrawCommandsStatesAddressNV)(const uint64_t * indirects, const int * sizes, const state * states, const framebuffer * fbos, unsigned int count) MYGL_NOEXCEPT;
extern void (*glDrawCommandsStatesNV)(buffer buffer, const ptrdiff_t * indirects, const int * sizes, const state * states, const framebuffer * fbos, unsigned int count) MYGL_NOEXCEPT;
extern void (*glDrawElements)(GLenum mode, int count, GLenum type, const void * indices) MYGL_NOEXCEPT;
extern void (*glDrawElementsBaseVertex)(GLenum mode, int count, GLenum type, const void * indices, int basevertex) MYGL_NOEXCEPT;
extern void (*glDrawElementsIndirect)(GLenum mode, GLenum type, const void * indirect) MYGL_NOEXCEPT;
extern void (*glDrawElementsInstanced)(GLenum mode, int count, GLenum type, const void * indices, int instancecount) MYGL_NOEXCEPT;
extern void (*glDrawElementsInstancedBaseInstance)(GLenum mode, int count, GLenum type, const void * indices, int instancecount, unsigned int baseinstance) MYGL_NOEXCEPT;
extern void (*glDrawElementsInstancedBaseVertex)(GLenum mode, int count, GLenum type, const void * indices, int instancecount, int basevertex) MYGL_NOEXCEPT;
extern void (*glDrawElementsInstancedBaseVertexBaseInstance)(GLenum mode, int count, GLenum type, const void * indices, int instancecount, int basevertex, unsigned int baseinstance) MYGL_NOEXCEPT;
extern void (*glDrawRangeElements)(GLenum mode, unsigned int start, unsigned int end, int count, GLenum type, const void * indices) MYGL_NOEXCEPT;
extern void (*glDrawRangeElementsBaseVertex)(GLenum mode, unsigned int start, unsigned int end, int count, GLenum type, const void * indices, int basevertex) MYGL_NOEXCEPT;
extern void (*glDrawTextureNV)(texture texture, sampler sampler, float x0, float y0, float x1, float y1, float z, float s0, float t0, float s1, float t1) MYGL_NOEXCEPT;
extern void (*glDrawTransformFeedback)(GLenum mode, transform_feedback id) MYGL_NOEXCEPT;
extern void (*glDrawTransformFeedbackInstanced)(GLenum mode, transform_feedback id, int instancecount) MYGL_NOEXCEPT;
extern void (*glDrawTransformFeedbackStream)(GLenum mode, transform_feedback id, unsigned int stream) MYGL_NOEXCEPT;
extern void (*glDrawTransformFeedbackStreamInstanced)(GLenum mode, transform_feedback id, unsigned int stream, int instancecount) MYGL_NOEXCEPT;
extern void (*glEdgeFlagFormatNV)(int stride) MYGL_NOEXCEPT;
extern void (*glEnable)(GLenum cap) MYGL_NOEXCEPT;
extern void (*glEnableClientState)(GLenum array) MYGL_NOEXCEPT;
extern void (*glEnableVertexArrayAttrib)(vertex_array vaobj, unsigned int index) MYGL_NOEXCEPT;
extern void (*glEnableVertexAttribArray)(unsigned int index) MYGL_NOEXCEPT;
extern void (*glEnablei)(GLenum target, unsigned int index) MYGL_NOEXCEPT;
extern void (*glEndConditionalRender)() MYGL_NOEXCEPT;
extern void (*glEndQuery)(GLenum target) MYGL_NOEXCEPT;
extern void (*glEndQueryIndexed)(GLenum target, unsigned int index) MYGL_NOEXCEPT;
extern void (*glEndTransformFeedback)() MYGL_NOEXCEPT;
extern GLsync(*glFenceSync)(GLenum condition, GLbitfield flags) MYGL_NOEXCEPT;
extern void (*glFinish)() MYGL_NOEXCEPT;
extern void (*glFlush)() MYGL_NOEXCEPT;
extern void (*glFlushMappedBufferRange)(GLenum target, ptrdiff_t offset, ptrdiff_t length) MYGL_NOEXCEPT;
extern void (*glFlushMappedNamedBufferRange)(buffer buffer, ptrdiff_t offset, ptrdiff_t length) MYGL_NOEXCEPT;
extern void (*glFogCoordFormatNV)(GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glFramebufferParameteri)(GLenum target, GLenum pname, int param) MYGL_NOEXCEPT;
extern void (*glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, renderbuffer renderbuffer) MYGL_NOEXCEPT;
extern void (*glFramebufferTexture)(GLenum target, GLenum attachment, texture texture, int level) MYGL_NOEXCEPT;
extern void (*glFramebufferTexture1D)(GLenum target, GLenum attachment, GLenum textarget, texture texture, int level) MYGL_NOEXCEPT;
extern void (*glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, texture texture, int level) MYGL_NOEXCEPT;
extern void (*glFramebufferTexture3D)(GLenum target, GLenum attachment, GLenum textarget, texture texture, int level, int zoffset) MYGL_NOEXCEPT;
extern void (*glFramebufferTextureLayer)(GLenum target, GLenum attachment, texture texture, int level, int layer) MYGL_NOEXCEPT;
extern void (*glFrontFace)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glGenBuffers)(int n, buffer * buffers) MYGL_NOEXCEPT;
extern void (*glGenFramebuffers)(int n, framebuffer * framebuffers) MYGL_NOEXCEPT;
extern path(*glGenPathsNV)(int range) MYGL_NOEXCEPT;
extern void (*glGenProgramPipelines)(int n, pipeline * pipelines) MYGL_NOEXCEPT;
extern void (*glGenQueries)(int n, query * ids) MYGL_NOEXCEPT;
extern void (*glGenRenderbuffers)(int n, renderbuffer * renderbuffers) MYGL_NOEXCEPT;
extern void (*glGenSamplers)(int count, sampler * samplers) MYGL_NOEXCEPT;
extern void (*glGenTextures)(int n, texture * textures) MYGL_NOEXCEPT;
extern void (*glGenTransformFeedbacks)(int n, transform_feedback * ids) MYGL_NOEXCEPT;
extern void (*glGenVertexArrays)(int n, vertex_array * arrays) MYGL_NOEXCEPT;
extern void (*glGenerateMipmap)(GLenum target) MYGL_NOEXCEPT;
extern void (*glGenerateTextureMipmap)(texture texture) MYGL_NOEXCEPT;
extern void (*glGetActiveAtomicCounterBufferiv)(shader_program program, unsigned int bufferIndex, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetActiveAttrib)(shader_program program, unsigned int index, int bufSize, int * length, int * size, GLenum * type, char * name) MYGL_NOEXCEPT;
extern void (*glGetActiveSubroutineName)(shader_program program, GLenum shadertype, unsigned int index, int bufsize, int * length, char * name) MYGL_NOEXCEPT;
extern void (*glGetActiveSubroutineUniformName)(shader_program program, GLenum shadertype, unsigned int index, int bufsize, int * length, char * name) MYGL_NOEXCEPT;
extern void (*glGetActiveSubroutineUniformiv)(shader_program program, GLenum shadertype, unsigned int index, GLenum pname, int * values) MYGL_NOEXCEPT;
extern void (*glGetActiveUniform)(shader_program program, unsigned int index, int bufSize, int * length, int * size, GLenum * type, char * name) MYGL_NOEXCEPT;
extern void (*glGetActiveUniformBlockName)(shader_program program, unsigned int uniformBlockIndex, int bufSize, int * length, char * uniformBlockName) MYGL_NOEXCEPT;
extern void (*glGetActiveUniformBlockiv)(shader_program program, unsigned int uniformBlockIndex, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetActiveUniformName)(shader_program program, unsigned int uniformIndex, int bufSize, int * length, char * uniformName) MYGL_NOEXCEPT;
extern void (*glGetActiveUniformsiv)(shader_program program, int uniformCount, const unsigned int * uniformIndices, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetAttachedShaders)(shader_program program, int maxCount, int * count, shader * shaders) MYGL_NOEXCEPT;
extern int(*glGetAttribLocation)(shader_program program, const char * name) MYGL_NOEXCEPT;
extern void (*glGetBooleani_v)(GLenum target, unsigned int index, bool * data) MYGL_NOEXCEPT;
extern void (*glGetBooleanv)(GLenum pname, bool * data) MYGL_NOEXCEPT;
extern void (*glGetBufferParameteri64v)(GLenum target, GLenum pname, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetBufferParameteriv)(GLenum target, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetBufferParameterui64vNV)(GLenum target, GLenum pname, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetBufferPointerv)(GLenum target, GLenum pname, void ** params) MYGL_NOEXCEPT;
extern void (*glGetBufferSubData)(GLenum target, ptrdiff_t offset, ptrdiff_t size, void * data) MYGL_NOEXCEPT;
extern unsigned int(*glGetCommandHeaderNV)(GLenum tokenID, unsigned int size) MYGL_NOEXCEPT;
extern void (*glGetCompressedTexImage)(GLenum target, int level, void * img) MYGL_NOEXCEPT;
extern void (*glGetCompressedTextureImage)(texture texture, int level, int bufSize, void * pixels) MYGL_NOEXCEPT;
extern void (*glGetCompressedTextureSubImage)(texture texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int bufSize, void * pixels) MYGL_NOEXCEPT;
extern unsigned int(*glGetDebugMessageLog)(unsigned int count, int bufSize, GLenum * sources, GLenum * types, unsigned int * ids, GLenum * severities, int * lengths, char * messageLog) MYGL_NOEXCEPT;
extern unsigned int(*glGetDebugMessageLogKHR)(unsigned int count, int bufSize, GLenum * sources, GLenum * types, unsigned int * ids, GLenum * severities, int * lengths, char * messageLog) MYGL_NOEXCEPT;
extern void (*glGetDoublei_v)(GLenum target, unsigned int index, double * data) MYGL_NOEXCEPT;
extern void (*glGetDoublev)(GLenum pname, double * data) MYGL_NOEXCEPT;
extern GLenum(*glGetError)() MYGL_NOEXCEPT;
extern void (*glGetFloati_v)(GLenum target, unsigned int index, float * data) MYGL_NOEXCEPT;
extern void (*glGetFloatv)(GLenum pname, float * data) MYGL_NOEXCEPT;
extern int(*glGetFragDataIndex)(shader_program program, const char * name) MYGL_NOEXCEPT;
extern int(*glGetFragDataLocation)(shader_program program, const char * name) MYGL_NOEXCEPT;
extern void (*glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetFramebufferParameteriv)(GLenum target, GLenum pname, int * params) MYGL_NOEXCEPT;
extern GLenum(*glGetGraphicsResetStatus)() MYGL_NOEXCEPT;
extern uint64_t(*glGetImageHandleARB)(texture texture, int level, bool layered, int layer, GLenum format) MYGL_NOEXCEPT;
extern void (*glGetInteger64i_v)(GLenum target, unsigned int index, int64_t * data) MYGL_NOEXCEPT;
extern void (*glGetInteger64v)(GLenum pname, int64_t * data) MYGL_NOEXCEPT;
extern void (*glGetIntegeri_v)(GLenum target, unsigned int index, int * data) MYGL_NOEXCEPT;
extern void (*glGetIntegerui64i_vNV)(GLenum value, unsigned int index, uint64_t * result) MYGL_NOEXCEPT;
extern void (*glGetIntegerui64vNV)(GLenum value, uint64_t * result) MYGL_NOEXCEPT;
extern void (*glGetIntegerv)(GLenum pname, int * data) MYGL_NOEXCEPT;
extern void (*glGetInternalformati64v)(GLenum target, GLenum internalformat, GLenum pname, int bufSize, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetInternalformativ)(GLenum target, GLenum internalformat, GLenum pname, int bufSize, int * params) MYGL_NOEXCEPT;
extern void (*glGetMultisamplefv)(GLenum pname, unsigned int index, float * val) MYGL_NOEXCEPT;
extern void (*glGetNamedBufferParameteri64v)(buffer buffer, GLenum pname, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetNamedBufferParameteriv)(buffer buffer, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetNamedBufferParameterui64vNV)(buffer buffer, GLenum pname, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetNamedBufferPointerv)(buffer buffer, GLenum pname, void ** params) MYGL_NOEXCEPT;
extern void (*glGetNamedBufferSubData)(buffer buffer, ptrdiff_t offset, ptrdiff_t size, void * data) MYGL_NOEXCEPT;
extern void (*glGetNamedFramebufferAttachmentParameteriv)(framebuffer framebuffer, GLenum attachment, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetNamedFramebufferParameteriv)(framebuffer framebuffer, GLenum pname, int * param) MYGL_NOEXCEPT;
extern void (*glGetNamedRenderbufferParameteriv)(renderbuffer renderbuffer, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetObjectLabel)(GLenum identifier, unsigned int name, int bufSize, int * length, char * label) MYGL_NOEXCEPT;
extern void (*glGetObjectLabelKHR)(GLenum identifier, unsigned int name, int bufSize, int * length, char * label) MYGL_NOEXCEPT;
extern void (*glGetObjectPtrLabel)(const void * ptr, int bufSize, int * length, char * label) MYGL_NOEXCEPT;
extern void (*glGetObjectPtrLabelKHR)(const void * ptr, int bufSize, int * length, char * label) MYGL_NOEXCEPT;
extern void (*glGetPathColorGenfvNV)(GLenum color, GLenum pname, float * value) MYGL_NOEXCEPT;
extern void (*glGetPathColorGenivNV)(GLenum color, GLenum pname, int * value) MYGL_NOEXCEPT;
extern void (*glGetPathCommandsNV)(path path, unsigned char * commands) MYGL_NOEXCEPT;
extern void (*glGetPathCoordsNV)(path path, float * coords) MYGL_NOEXCEPT;
extern void (*glGetPathDashArrayNV)(path path, float * dashArray) MYGL_NOEXCEPT;
extern float(*glGetPathLengthNV)(path path, int startSegment, int numSegments) MYGL_NOEXCEPT;
extern void (*glGetPathMetricRangeNV)(GLbitfield metricQueryMask, path firstPathName, int numPaths, int stride, float * metrics) MYGL_NOEXCEPT;
extern void (*glGetPathMetricsNV)(GLbitfield metricQueryMask, int numPaths, GLenum pathNameType, const void * paths, path pathBase, int stride, float * metrics) MYGL_NOEXCEPT;
extern void (*glGetPathParameterfvNV)(path path, GLenum pname, float * value) MYGL_NOEXCEPT;
extern void (*glGetPathParameterivNV)(path path, GLenum pname, int * value) MYGL_NOEXCEPT;
extern void (*glGetPathSpacingNV)(GLenum pathListMode, int numPaths, GLenum pathNameType, const void * paths, path pathBase, float advanceScale, float kerningScale, GLenum transformType, float * returnedSpacing) MYGL_NOEXCEPT;
extern void (*glGetPathTexGenfvNV)(GLenum texCoordSet, GLenum pname, float * value) MYGL_NOEXCEPT;
extern void (*glGetPathTexGenivNV)(GLenum texCoordSet, GLenum pname, int * value) MYGL_NOEXCEPT;
extern void (*glGetPointerv)(GLenum pname, void ** params) MYGL_NOEXCEPT;
extern void (*glGetPointervKHR)(GLenum pname, void ** params) MYGL_NOEXCEPT;
extern void (*glGetProgramBinary)(shader_program program, int bufSize, int * length, GLenum * binaryFormat, void * binary) MYGL_NOEXCEPT;
extern void (*glGetProgramInfoLog)(shader_program program, int bufSize, int * length, char * infoLog) MYGL_NOEXCEPT;
extern void (*glGetProgramInterfaceiv)(shader_program program, GLenum programInterface, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetProgramPipelineInfoLog)(pipeline pipeline, int bufSize, int * length, char * infoLog) MYGL_NOEXCEPT;
extern void (*glGetProgramPipelineiv)(pipeline pipeline, GLenum pname, int * params) MYGL_NOEXCEPT;
extern unsigned int(*glGetProgramResourceIndex)(shader_program program, GLenum programInterface, const char * name) MYGL_NOEXCEPT;
extern int(*glGetProgramResourceLocation)(shader_program program, GLenum programInterface, const char * name) MYGL_NOEXCEPT;
extern int(*glGetProgramResourceLocationIndex)(shader_program program, GLenum programInterface, const char * name) MYGL_NOEXCEPT;
extern void (*glGetProgramResourceName)(shader_program program, GLenum programInterface, unsigned int index, int bufSize, int * length, char * name) MYGL_NOEXCEPT;
extern void (*glGetProgramResourcefvNV)(shader_program program, GLenum programInterface, unsigned int index, int propCount, const GLenum * props, int bufSize, int * length, float * params) MYGL_NOEXCEPT;
extern void (*glGetProgramResourceiv)(shader_program program, GLenum programInterface, unsigned int index, int propCount, const GLenum * props, int bufSize, int * length, int * params) MYGL_NOEXCEPT;
extern void (*glGetProgramStageiv)(shader_program program, GLenum shadertype, GLenum pname, int * values) MYGL_NOEXCEPT;
extern void (*glGetProgramSubroutineParameteruivNV)(GLenum target, unsigned int index, unsigned int * param) MYGL_NOEXCEPT;
extern void (*glGetProgramiv)(shader_program program, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetQueryBufferObjecti64v)(query id, buffer buffer, GLenum pname, ptrdiff_t offset) MYGL_NOEXCEPT;
extern void (*glGetQueryBufferObjectiv)(query id, buffer buffer, GLenum pname, ptrdiff_t offset) MYGL_NOEXCEPT;
extern void (*glGetQueryBufferObjectui64v)(query id, buffer buffer, GLenum pname, ptrdiff_t offset) MYGL_NOEXCEPT;
extern void (*glGetQueryBufferObjectuiv)(query id, buffer buffer, GLenum pname, ptrdiff_t offset) MYGL_NOEXCEPT;
extern void (*glGetQueryIndexediv)(GLenum target, unsigned int index, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetQueryObjecti64v)(query id, GLenum pname, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetQueryObjectiv)(query id, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetQueryObjectui64v)(query id, GLenum pname, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetQueryObjectuiv)(query id, GLenum pname, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetQueryiv)(GLenum target, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetRenderbufferParameteriv)(GLenum target, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetSamplerParameterIiv)(sampler sampler, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetSamplerParameterIuiv)(sampler sampler, GLenum pname, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetSamplerParameterfv)(sampler sampler, GLenum pname, float * params) MYGL_NOEXCEPT;
extern void (*glGetSamplerParameteriv)(sampler sampler, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetShaderInfoLog)(shader shader, int bufSize, int * length, char * infoLog) MYGL_NOEXCEPT;
extern void (*glGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, int * range, int * precision) MYGL_NOEXCEPT;
extern void (*glGetShaderSource)(shader shader, int bufSize, int * length, char * source) MYGL_NOEXCEPT;
extern void (*glGetShaderiv)(shader shader, GLenum pname, int * params) MYGL_NOEXCEPT;
extern unsigned short(*glGetStageIndexNV)(GLenum shadertype) MYGL_NOEXCEPT;
extern const unsigned char *(*glGetString)(GLenum name) MYGL_NOEXCEPT;
extern const unsigned char *(*glGetStringi)(GLenum name, unsigned int index) MYGL_NOEXCEPT;
extern unsigned int(*glGetSubroutineIndex)(shader_program program, GLenum shadertype, const char * name) MYGL_NOEXCEPT;
extern int(*glGetSubroutineUniformLocation)(shader_program program, GLenum shadertype, const char * name) MYGL_NOEXCEPT;
extern void (*glGetSynciv)(GLsync sync, GLenum pname, int bufSize, int * length, int * values) MYGL_NOEXCEPT;
extern void (*glGetTexImage)(GLenum target, int level, GLenum format, GLenum type, void * pixels) MYGL_NOEXCEPT;
extern void (*glGetTexLevelParameterfv)(GLenum target, int level, GLenum pname, float * params) MYGL_NOEXCEPT;
extern void (*glGetTexLevelParameteriv)(GLenum target, int level, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetTexParameterIiv)(GLenum target, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetTexParameterIuiv)(GLenum target, GLenum pname, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetTexParameterfv)(GLenum target, GLenum pname, float * params) MYGL_NOEXCEPT;
extern void (*glGetTexParameteriv)(GLenum target, GLenum pname, int * params) MYGL_NOEXCEPT;
extern uint64_t(*glGetTextureHandleARB)(texture texture) MYGL_NOEXCEPT;
extern void (*glGetTextureImage)(texture texture, int level, GLenum format, GLenum type, int bufSize, void * pixels) MYGL_NOEXCEPT;
extern void (*glGetTextureLevelParameterfv)(texture texture, int level, GLenum pname, float * params) MYGL_NOEXCEPT;
extern void (*glGetTextureLevelParameteriv)(texture texture, int level, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetTextureParameterIiv)(texture texture, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetTextureParameterIuiv)(texture texture, GLenum pname, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetTextureParameterfv)(texture texture, GLenum pname, float * params) MYGL_NOEXCEPT;
extern void (*glGetTextureParameteriv)(texture texture, GLenum pname, int * params) MYGL_NOEXCEPT;
extern uint64_t(*glGetTextureSamplerHandleARB)(texture texture, sampler sampler) MYGL_NOEXCEPT;
extern void (*glGetTextureSubImage)(texture texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, GLenum format, GLenum type, int bufSize, void * pixels) MYGL_NOEXCEPT;
extern void (*glGetTransformFeedbackVarying)(shader_program program, unsigned int index, int bufSize, int * length, int * size, GLenum * type, char * name) MYGL_NOEXCEPT;
extern void (*glGetTransformFeedbacki64_v)(transform_feedback xfb, GLenum pname, unsigned int index, int64_t * param) MYGL_NOEXCEPT;
extern void (*glGetTransformFeedbacki_v)(transform_feedback xfb, GLenum pname, unsigned int index, int * param) MYGL_NOEXCEPT;
extern void (*glGetTransformFeedbackiv)(transform_feedback xfb, GLenum pname, int * param) MYGL_NOEXCEPT;
extern unsigned int(*glGetUniformBlockIndex)(shader_program program, const char * uniformBlockName) MYGL_NOEXCEPT;
extern void (*glGetUniformIndices)(shader_program program, int uniformCount, const char *const* uniformNames, unsigned int * uniformIndices) MYGL_NOEXCEPT;
extern int(*glGetUniformLocation)(shader_program program, const char * name) MYGL_NOEXCEPT;
extern void (*glGetUniformSubroutineuiv)(GLenum shadertype, int location, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetUniformdv)(shader_program program, int location, double * params) MYGL_NOEXCEPT;
extern void (*glGetUniformfv)(shader_program program, int location, float * params) MYGL_NOEXCEPT;
extern void (*glGetUniformi64vARB)(shader_program program, int location, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetUniformi64vNV)(shader_program program, int location, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetUniformiv)(shader_program program, int location, int * params) MYGL_NOEXCEPT;
extern void (*glGetUniformui64vARB)(shader_program program, int location, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetUniformui64vNV)(shader_program program, int location, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetUniformuiv)(shader_program program, int location, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetVertexArrayIndexed64iv)(vertex_array vaobj, unsigned int index, GLenum pname, int64_t * param) MYGL_NOEXCEPT;
extern void (*glGetVertexArrayIndexediv)(vertex_array vaobj, unsigned int index, GLenum pname, int * param) MYGL_NOEXCEPT;
extern void (*glGetVertexArrayiv)(vertex_array vaobj, GLenum pname, int * param) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribIiv)(unsigned int index, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribIuiv)(unsigned int index, GLenum pname, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribLdv)(unsigned int index, GLenum pname, double * params) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribLui64vARB)(unsigned int index, GLenum pname, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribPointerv)(unsigned int index, GLenum pname, void ** pointer) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribdv)(unsigned int index, GLenum pname, double * params) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribfv)(unsigned int index, GLenum pname, float * params) MYGL_NOEXCEPT;
extern void (*glGetVertexAttribiv)(unsigned int index, GLenum pname, int * params) MYGL_NOEXCEPT;
extern void (*glGetnCompressedTexImage)(GLenum target, int lod, int bufSize, void * pixels) MYGL_NOEXCEPT;
extern void (*glGetnTexImage)(GLenum target, int level, GLenum format, GLenum type, int bufSize, void * pixels) MYGL_NOEXCEPT;
extern void (*glGetnUniformdv)(shader_program program, int location, int bufSize, double * params) MYGL_NOEXCEPT;
extern void (*glGetnUniformfv)(shader_program program, int location, int bufSize, float * params) MYGL_NOEXCEPT;
extern void (*glGetnUniformi64vARB)(shader_program program, int location, int bufSize, int64_t * params) MYGL_NOEXCEPT;
extern void (*glGetnUniformiv)(shader_program program, int location, int bufSize, int * params) MYGL_NOEXCEPT;
extern void (*glGetnUniformui64vARB)(shader_program program, int location, int bufSize, uint64_t * params) MYGL_NOEXCEPT;
extern void (*glGetnUniformuiv)(shader_program program, int location, int bufSize, unsigned int * params) MYGL_NOEXCEPT;
extern void (*glHint)(GLenum target, GLenum mode) MYGL_NOEXCEPT;
extern void (*glIndexFormatNV)(GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glInterpolatePathsNV)(path resultPath, unsigned int pathA, unsigned int pathB, float weight) MYGL_NOEXCEPT;
extern void (*glInvalidateBufferData)(buffer buffer) MYGL_NOEXCEPT;
extern void (*glInvalidateBufferSubData)(buffer buffer, ptrdiff_t offset, ptrdiff_t length) MYGL_NOEXCEPT;
extern void (*glInvalidateFramebuffer)(GLenum target, int numAttachments, const GLenum * attachments) MYGL_NOEXCEPT;
extern void (*glInvalidateNamedFramebufferData)(framebuffer framebuffer, int numAttachments, const GLenum * attachments) MYGL_NOEXCEPT;
extern void (*glInvalidateNamedFramebufferSubData)(framebuffer framebuffer, int numAttachments, const GLenum * attachments, int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glInvalidateSubFramebuffer)(GLenum target, int numAttachments, const GLenum * attachments, int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glInvalidateTexImage)(texture texture, int level) MYGL_NOEXCEPT;
extern void (*glInvalidateTexSubImage)(texture texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth) MYGL_NOEXCEPT;
extern bool(*glIsBuffer)(buffer buffer) MYGL_NOEXCEPT;
extern bool(*glIsBufferResidentNV)(GLenum target) MYGL_NOEXCEPT;
extern bool(*glIsCommandListNV)(command_list list) MYGL_NOEXCEPT;
extern bool(*glIsEnabled)(GLenum cap) MYGL_NOEXCEPT;
extern bool(*glIsEnabledi)(GLenum target, unsigned int index) MYGL_NOEXCEPT;
extern bool(*glIsFramebuffer)(framebuffer framebuffer) MYGL_NOEXCEPT;
extern bool(*glIsImageHandleResidentARB)(uint64_t handle) MYGL_NOEXCEPT;
extern bool(*glIsNamedBufferResidentNV)(buffer buffer) MYGL_NOEXCEPT;
extern bool(*glIsPathNV)(path path) MYGL_NOEXCEPT;
extern bool(*glIsPointInFillPathNV)(path path, unsigned int mask, float x, float y) MYGL_NOEXCEPT;
extern bool(*glIsPointInStrokePathNV)(path path, float x, float y) MYGL_NOEXCEPT;
extern bool(*glIsProgram)(shader_program program) MYGL_NOEXCEPT;
extern bool(*glIsProgramPipeline)(pipeline pipeline) MYGL_NOEXCEPT;
extern bool(*glIsQuery)(query id) MYGL_NOEXCEPT;
extern bool(*glIsRenderbuffer)(renderbuffer renderbuffer) MYGL_NOEXCEPT;
extern bool(*glIsSampler)(sampler sampler) MYGL_NOEXCEPT;
extern bool(*glIsShader)(shader shader) MYGL_NOEXCEPT;
extern bool(*glIsStateNV)(state state) MYGL_NOEXCEPT;
extern bool(*glIsSync)(GLsync sync) MYGL_NOEXCEPT;
extern bool(*glIsTexture)(texture texture) MYGL_NOEXCEPT;
extern bool(*glIsTextureHandleResidentARB)(uint64_t handle) MYGL_NOEXCEPT;
extern bool(*glIsTransformFeedback)(transform_feedback id) MYGL_NOEXCEPT;
extern bool(*glIsVertexArray)(vertex_array array) MYGL_NOEXCEPT;
extern void (*glLineWidth)(float width) MYGL_NOEXCEPT;
extern void (*glLinkProgram)(shader_program program) MYGL_NOEXCEPT;
extern void (*glListDrawCommandsStatesClientNV)(command_list list, unsigned int segment, const void ** indirects, const int * sizes, const state * states, const framebuffer * fbos, unsigned int count) MYGL_NOEXCEPT;
extern void (*glLogicOp)(GLenum opcode) MYGL_NOEXCEPT;
extern void (*glMakeBufferNonResidentNV)(GLenum target) MYGL_NOEXCEPT;
extern void (*glMakeBufferResidentNV)(GLenum target, GLenum access) MYGL_NOEXCEPT;
extern void (*glMakeImageHandleNonResidentARB)(uint64_t handle) MYGL_NOEXCEPT;
extern void (*glMakeImageHandleResidentARB)(uint64_t handle, GLenum access) MYGL_NOEXCEPT;
extern void (*glMakeNamedBufferNonResidentNV)(buffer buffer) MYGL_NOEXCEPT;
extern void (*glMakeNamedBufferResidentNV)(buffer buffer, GLenum access) MYGL_NOEXCEPT;
extern void (*glMakeTextureHandleNonResidentARB)(uint64_t handle) MYGL_NOEXCEPT;
extern void (*glMakeTextureHandleResidentARB)(uint64_t handle) MYGL_NOEXCEPT;
extern void *(*glMapBuffer)(GLenum target, GLenum access) MYGL_NOEXCEPT;
extern void *(*glMapBufferRange)(GLenum target, ptrdiff_t offset, ptrdiff_t length, GLbitfield access) MYGL_NOEXCEPT;
extern void *(*glMapNamedBuffer)(buffer buffer, GLenum access) MYGL_NOEXCEPT;
extern void *(*glMapNamedBufferRange)(buffer buffer, ptrdiff_t offset, ptrdiff_t length, GLbitfield access) MYGL_NOEXCEPT;
extern void (*glMatrixFrustumEXT)(GLenum mode, double left, double right, double bottom, double top, double zNear, double zFar) MYGL_NOEXCEPT;
extern void (*glMatrixLoad3x2fNV)(GLenum matrixMode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixLoad3x3fNV)(GLenum matrixMode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixLoadIdentityEXT)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glMatrixLoadTranspose3x3fNV)(GLenum matrixMode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixLoadTransposedEXT)(GLenum mode, const double * m) MYGL_NOEXCEPT;
extern void (*glMatrixLoadTransposefEXT)(GLenum mode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixLoaddEXT)(GLenum mode, const double * m) MYGL_NOEXCEPT;
extern void (*glMatrixLoadfEXT)(GLenum mode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixMult3x2fNV)(GLenum matrixMode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixMult3x3fNV)(GLenum matrixMode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixMultTranspose3x3fNV)(GLenum matrixMode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixMultTransposedEXT)(GLenum mode, const double * m) MYGL_NOEXCEPT;
extern void (*glMatrixMultTransposefEXT)(GLenum mode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixMultdEXT)(GLenum mode, const double * m) MYGL_NOEXCEPT;
extern void (*glMatrixMultfEXT)(GLenum mode, const float * m) MYGL_NOEXCEPT;
extern void (*glMatrixOrthoEXT)(GLenum mode, double left, double right, double bottom, double top, double zNear, double zFar) MYGL_NOEXCEPT;
extern void (*glMatrixPopEXT)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glMatrixPushEXT)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glMatrixRotatedEXT)(GLenum mode, double angle, double x, double y, double z) MYGL_NOEXCEPT;
extern void (*glMatrixRotatefEXT)(GLenum mode, float angle, float x, float y, float z) MYGL_NOEXCEPT;
extern void (*glMatrixScaledEXT)(GLenum mode, double x, double y, double z) MYGL_NOEXCEPT;
extern void (*glMatrixScalefEXT)(GLenum mode, float x, float y, float z) MYGL_NOEXCEPT;
extern void (*glMatrixTranslatedEXT)(GLenum mode, double x, double y, double z) MYGL_NOEXCEPT;
extern void (*glMatrixTranslatefEXT)(GLenum mode, float x, float y, float z) MYGL_NOEXCEPT;
extern void (*glMemoryBarrier)(GLbitfield barriers) MYGL_NOEXCEPT;
extern void (*glMemoryBarrierByRegion)(GLbitfield barriers) MYGL_NOEXCEPT;
extern void (*glMinSampleShading)(float value) MYGL_NOEXCEPT;
extern void (*glMultiDrawArrays)(GLenum mode, const int * first, const int * count, int drawcount) MYGL_NOEXCEPT;
extern void (*glMultiDrawArraysIndirect)(GLenum mode, const void * indirect, int drawcount, int stride) MYGL_NOEXCEPT;
extern void (*glMultiDrawArraysIndirectBindlessCountNV)(GLenum mode, const void * indirect, int drawCount, int maxDrawCount, int stride, int vertexBufferCount) MYGL_NOEXCEPT;
extern void (*glMultiDrawArraysIndirectBindlessNV)(GLenum mode, const void * indirect, int drawCount, int stride, int vertexBufferCount) MYGL_NOEXCEPT;
extern void (*glMultiDrawArraysIndirectCount)(GLenum mode, const void * indirect, ptrdiff_t drawcount, int maxdrawcount, int stride) MYGL_NOEXCEPT;
extern void (*glMultiDrawElements)(GLenum mode, const int * count, GLenum type, const void *const* indices, int drawcount) MYGL_NOEXCEPT;
extern void (*glMultiDrawElementsBaseVertex)(GLenum mode, const int * count, GLenum type, const void *const* indices, int drawcount, const int * basevertex) MYGL_NOEXCEPT;
extern void (*glMultiDrawElementsIndirect)(GLenum mode, GLenum type, const void * indirect, int drawcount, int stride) MYGL_NOEXCEPT;
extern void (*glMultiDrawElementsIndirectBindlessCountNV)(GLenum mode, GLenum type, const void * indirect, int drawCount, int maxDrawCount, int stride, int vertexBufferCount) MYGL_NOEXCEPT;
extern void (*glMultiDrawElementsIndirectBindlessNV)(GLenum mode, GLenum type, const void * indirect, int drawCount, int stride, int vertexBufferCount) MYGL_NOEXCEPT;
extern void (*glMultiDrawElementsIndirectCount)(GLenum mode, GLenum type, const void * indirect, ptrdiff_t drawcount, int maxdrawcount, int stride) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP1ui)(texture texture, GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP1uiv)(texture texture, GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP2ui)(texture texture, GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP2uiv)(texture texture, GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP3ui)(texture texture, GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP3uiv)(texture texture, GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP4ui)(texture texture, GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glMultiTexCoordP4uiv)(texture texture, GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glNamedBufferData)(buffer buffer, ptrdiff_t size, const void * data, GLenum usage) MYGL_NOEXCEPT;
extern void (*glNamedBufferStorage)(buffer buffer, ptrdiff_t size, const void * data, GLbitfield flags) MYGL_NOEXCEPT;
extern void (*glNamedBufferSubData)(buffer buffer, ptrdiff_t offset, ptrdiff_t size, const void * data) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferDrawBuffer)(framebuffer framebuffer, GLenum buf) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferDrawBuffers)(framebuffer framebuffer, int n, const GLenum * bufs) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferParameteri)(framebuffer framebuffer, GLenum pname, int param) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferReadBuffer)(framebuffer framebuffer, GLenum src) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferRenderbuffer)(framebuffer framebuffer, GLenum attachment, GLenum renderbuffertarget, renderbuffer renderbuffer) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferTexture)(framebuffer framebuffer, GLenum attachment, texture texture, int level) MYGL_NOEXCEPT;
extern void (*glNamedFramebufferTextureLayer)(framebuffer framebuffer, GLenum attachment, texture texture, int level, int layer) MYGL_NOEXCEPT;
extern void (*glNamedRenderbufferStorage)(renderbuffer renderbuffer, GLenum internalformat, int width, int height) MYGL_NOEXCEPT;
extern void (*glNamedRenderbufferStorageMultisample)(renderbuffer renderbuffer, int samples, GLenum internalformat, int width, int height) MYGL_NOEXCEPT;
extern void (*glNormalFormatNV)(GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glNormalP3ui)(GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glNormalP3uiv)(GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glObjectLabel)(GLenum identifier, unsigned int name, int length, const char * label) MYGL_NOEXCEPT;
extern void (*glObjectLabelKHR)(GLenum identifier, unsigned int name, int length, const char * label) MYGL_NOEXCEPT;
extern void (*glObjectPtrLabel)(const void * ptr, int length, const char * label) MYGL_NOEXCEPT;
extern void (*glObjectPtrLabelKHR)(const void * ptr, int length, const char * label) MYGL_NOEXCEPT;
extern void (*glPatchParameterfv)(GLenum pname, const float * values) MYGL_NOEXCEPT;
extern void (*glPatchParameteri)(GLenum pname, int value) MYGL_NOEXCEPT;
extern void (*glPathColorGenNV)(GLenum color, GLenum genMode, GLenum colorFormat, const float * coeffs) MYGL_NOEXCEPT;
extern void (*glPathCommandsNV)(path path, int numCommands, const unsigned char * commands, int numCoords, GLenum coordType, const void * coords) MYGL_NOEXCEPT;
extern void (*glPathCoordsNV)(path path, int numCoords, GLenum coordType, const void * coords) MYGL_NOEXCEPT;
extern void (*glPathCoverDepthFuncNV)(GLenum func) MYGL_NOEXCEPT;
extern void (*glPathDashArrayNV)(path path, int dashCount, const float * dashArray) MYGL_NOEXCEPT;
extern void (*glPathFogGenNV)(GLenum genMode) MYGL_NOEXCEPT;
extern GLenum(*glPathGlyphIndexArrayNV)(path firstPathName, GLenum fontTarget, const void * fontName, GLbitfield fontStyle, unsigned int firstGlyphIndex, int numGlyphs, unsigned int pathParameterTemplate, float emScale) MYGL_NOEXCEPT;
extern GLenum(*glPathGlyphIndexRangeNV)(GLenum fontTarget, const void * fontName, GLbitfield fontStyle, unsigned int pathParameterTemplate, float emScale, unsigned int baseAndCount[2]) MYGL_NOEXCEPT;
extern void (*glPathGlyphRangeNV)(path firstPathName, GLenum fontTarget, const void * fontName, GLbitfield fontStyle, unsigned int firstGlyph, int numGlyphs, GLenum handleMissingGlyphs, unsigned int pathParameterTemplate, float emScale) MYGL_NOEXCEPT;
extern void (*glPathGlyphsNV)(path firstPathName, GLenum fontTarget, const void * fontName, GLbitfield fontStyle, int numGlyphs, GLenum type, const void * charcodes, GLenum handleMissingGlyphs, unsigned int pathParameterTemplate, float emScale) MYGL_NOEXCEPT;
extern GLenum(*glPathMemoryGlyphIndexArrayNV)(path firstPathName, GLenum fontTarget, ptrdiff_t fontSize, const void * fontData, int faceIndex, unsigned int firstGlyphIndex, int numGlyphs, unsigned int pathParameterTemplate, float emScale) MYGL_NOEXCEPT;
extern void (*glPathParameterfNV)(path path, GLenum pname, float value) MYGL_NOEXCEPT;
extern void (*glPathParameterfvNV)(path path, GLenum pname, const float * value) MYGL_NOEXCEPT;
extern void (*glPathParameteriNV)(path path, GLenum pname, int value) MYGL_NOEXCEPT;
extern void (*glPathParameterivNV)(path path, GLenum pname, const int * value) MYGL_NOEXCEPT;
extern void (*glPathStencilDepthOffsetNV)(float factor, float units) MYGL_NOEXCEPT;
extern void (*glPathStencilFuncNV)(GLenum func, int ref, unsigned int mask) MYGL_NOEXCEPT;
extern void (*glPathStringNV)(path path, GLenum format, int length, const void * pathString) MYGL_NOEXCEPT;
extern void (*glPathSubCommandsNV)(path path, int commandStart, int commandsToDelete, int numCommands, const unsigned char * commands, int numCoords, GLenum coordType, const void * coords) MYGL_NOEXCEPT;
extern void (*glPathSubCoordsNV)(path path, int coordStart, int numCoords, GLenum coordType, const void * coords) MYGL_NOEXCEPT;
extern void (*glPathTexGenNV)(GLenum texCoordSet, GLenum genMode, int components, const float * coeffs) MYGL_NOEXCEPT;
extern void (*glPauseTransformFeedback)() MYGL_NOEXCEPT;
extern void (*glPixelStoref)(GLenum pname, float param) MYGL_NOEXCEPT;
extern void (*glPixelStorei)(GLenum pname, int param) MYGL_NOEXCEPT;
extern bool(*glPointAlongPathNV)(path path, int startSegment, int numSegments, float distance, float * x, float * y, float * tangentX, float * tangentY) MYGL_NOEXCEPT;
extern void (*glPointParameterf)(GLenum pname, float param) MYGL_NOEXCEPT;
extern void (*glPointParameterfv)(GLenum pname, const float * params) MYGL_NOEXCEPT;
extern void (*glPointParameteri)(GLenum pname, int param) MYGL_NOEXCEPT;
extern void (*glPointParameteriv)(GLenum pname, const int * params) MYGL_NOEXCEPT;
extern void (*glPointSize)(float size) MYGL_NOEXCEPT;
extern void (*glPolygonMode)(GLenum face, GLenum mode) MYGL_NOEXCEPT;
extern void (*glPolygonOffset)(float factor, float units) MYGL_NOEXCEPT;
extern void (*glPolygonOffsetClamp)(float factor, float units, float clamp) MYGL_NOEXCEPT;
extern void (*glPopDebugGroup)() MYGL_NOEXCEPT;
extern void (*glPopDebugGroupKHR)() MYGL_NOEXCEPT;
extern void (*glPrimitiveRestartIndex)(unsigned int index) MYGL_NOEXCEPT;
extern void (*glProgramBinary)(shader_program program, GLenum binaryFormat, const void * binary, int length) MYGL_NOEXCEPT;
extern void (*glProgramParameteri)(shader_program program, GLenum pname, int value) MYGL_NOEXCEPT;
extern void (*glProgramPathFragmentInputGenNV)(shader_program program, int location, GLenum genMode, int components, const float * coeffs) MYGL_NOEXCEPT;
extern void (*glProgramSubroutineParametersuivNV)(GLenum target, int count, const unsigned int * params) MYGL_NOEXCEPT;
extern void (*glProgramUniform1d)(shader_program program, int location, double v0) MYGL_NOEXCEPT;
extern void (*glProgramUniform1dv)(shader_program program, int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1f)(shader_program program, int location, float v0) MYGL_NOEXCEPT;
extern void (*glProgramUniform1fv)(shader_program program, int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1i)(shader_program program, int location, int v0) MYGL_NOEXCEPT;
extern void (*glProgramUniform1i64ARB)(shader_program program, int location, int64_t x) MYGL_NOEXCEPT;
extern void (*glProgramUniform1i64NV)(shader_program program, int location, int64_t x) MYGL_NOEXCEPT;
extern void (*glProgramUniform1i64vARB)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1i64vNV)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1iv)(shader_program program, int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1ui)(shader_program program, int location, unsigned int v0) MYGL_NOEXCEPT;
extern void (*glProgramUniform1ui64ARB)(shader_program program, int location, uint64_t x) MYGL_NOEXCEPT;
extern void (*glProgramUniform1ui64NV)(shader_program program, int location, uint64_t x) MYGL_NOEXCEPT;
extern void (*glProgramUniform1ui64vARB)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1ui64vNV)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform1uiv)(shader_program program, int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2d)(shader_program program, int location, double v0, double v1) MYGL_NOEXCEPT;
extern void (*glProgramUniform2dv)(shader_program program, int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2f)(shader_program program, int location, float v0, float v1) MYGL_NOEXCEPT;
extern void (*glProgramUniform2fv)(shader_program program, int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2i)(shader_program program, int location, int v0, int v1) MYGL_NOEXCEPT;
extern void (*glProgramUniform2i64ARB)(shader_program program, int location, int64_t x, int64_t y) MYGL_NOEXCEPT;
extern void (*glProgramUniform2i64NV)(shader_program program, int location, int64_t x, int64_t y) MYGL_NOEXCEPT;
extern void (*glProgramUniform2i64vARB)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2i64vNV)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2iv)(shader_program program, int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2ui)(shader_program program, int location, unsigned int v0, unsigned int v1) MYGL_NOEXCEPT;
extern void (*glProgramUniform2ui64ARB)(shader_program program, int location, uint64_t x, uint64_t y) MYGL_NOEXCEPT;
extern void (*glProgramUniform2ui64NV)(shader_program program, int location, uint64_t x, uint64_t y) MYGL_NOEXCEPT;
extern void (*glProgramUniform2ui64vARB)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2ui64vNV)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform2uiv)(shader_program program, int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3d)(shader_program program, int location, double v0, double v1, double v2) MYGL_NOEXCEPT;
extern void (*glProgramUniform3dv)(shader_program program, int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3f)(shader_program program, int location, float v0, float v1, float v2) MYGL_NOEXCEPT;
extern void (*glProgramUniform3fv)(shader_program program, int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3i)(shader_program program, int location, int v0, int v1, int v2) MYGL_NOEXCEPT;
extern void (*glProgramUniform3i64ARB)(shader_program program, int location, int64_t x, int64_t y, int64_t z) MYGL_NOEXCEPT;
extern void (*glProgramUniform3i64NV)(shader_program program, int location, int64_t x, int64_t y, int64_t z) MYGL_NOEXCEPT;
extern void (*glProgramUniform3i64vARB)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3i64vNV)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3iv)(shader_program program, int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3ui)(shader_program program, int location, unsigned int v0, unsigned int v1, unsigned int v2) MYGL_NOEXCEPT;
extern void (*glProgramUniform3ui64ARB)(shader_program program, int location, uint64_t x, uint64_t y, uint64_t z) MYGL_NOEXCEPT;
extern void (*glProgramUniform3ui64NV)(shader_program program, int location, uint64_t x, uint64_t y, uint64_t z) MYGL_NOEXCEPT;
extern void (*glProgramUniform3ui64vARB)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3ui64vNV)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform3uiv)(shader_program program, int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4d)(shader_program program, int location, double v0, double v1, double v2, double v3) MYGL_NOEXCEPT;
extern void (*glProgramUniform4dv)(shader_program program, int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4f)(shader_program program, int location, float v0, float v1, float v2, float v3) MYGL_NOEXCEPT;
extern void (*glProgramUniform4fv)(shader_program program, int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4i)(shader_program program, int location, int v0, int v1, int v2, int v3) MYGL_NOEXCEPT;
extern void (*glProgramUniform4i64ARB)(shader_program program, int location, int64_t x, int64_t y, int64_t z, int64_t w) MYGL_NOEXCEPT;
extern void (*glProgramUniform4i64NV)(shader_program program, int location, int64_t x, int64_t y, int64_t z, int64_t w) MYGL_NOEXCEPT;
extern void (*glProgramUniform4i64vARB)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4i64vNV)(shader_program program, int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4iv)(shader_program program, int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4ui)(shader_program program, int location, unsigned int v0, unsigned int v1, unsigned int v2, unsigned int v3) MYGL_NOEXCEPT;
extern void (*glProgramUniform4ui64ARB)(shader_program program, int location, uint64_t x, uint64_t y, uint64_t z, uint64_t w) MYGL_NOEXCEPT;
extern void (*glProgramUniform4ui64NV)(shader_program program, int location, uint64_t x, uint64_t y, uint64_t z, uint64_t w) MYGL_NOEXCEPT;
extern void (*glProgramUniform4ui64vARB)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4ui64vNV)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProgramUniform4uiv)(shader_program program, int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformHandleui64ARB)(shader_program program, int location, uint64_t value) MYGL_NOEXCEPT;
extern void (*glProgramUniformHandleui64vARB)(shader_program program, int location, int count, const uint64_t * values) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix2dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix2fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix2x3dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix2x3fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix2x4dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix2x4fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix3dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix3fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix3x2dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix3x2fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix3x4dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix3x4fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix4dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix4fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix4x2dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix4x2fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix4x3dv)(shader_program program, int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformMatrix4x3fv)(shader_program program, int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glProgramUniformui64NV)(shader_program program, int location, uint64_t value) MYGL_NOEXCEPT;
extern void (*glProgramUniformui64vNV)(shader_program program, int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glProvokingVertex)(GLenum mode) MYGL_NOEXCEPT;
extern void (*glPushDebugGroup)(GLenum source, unsigned int id, int length, const char * message) MYGL_NOEXCEPT;
extern void (*glPushDebugGroupKHR)(GLenum source, unsigned int id, int length, const char * message) MYGL_NOEXCEPT;
extern void (*glQueryCounter)(query id, GLenum target) MYGL_NOEXCEPT;
extern void (*glReadBuffer)(GLenum src) MYGL_NOEXCEPT;
extern void (*glReadPixels)(int x, int y, int width, int height, GLenum format, GLenum type, void * pixels) MYGL_NOEXCEPT;
extern void (*glReadnPixels)(int x, int y, int width, int height, GLenum format, GLenum type, int bufSize, void * data) MYGL_NOEXCEPT;
extern void (*glReleaseShaderCompiler)() MYGL_NOEXCEPT;
extern void (*glRenderbufferStorage)(GLenum target, GLenum internalformat, int width, int height) MYGL_NOEXCEPT;
extern void (*glRenderbufferStorageMultisample)(GLenum target, int samples, GLenum internalformat, int width, int height) MYGL_NOEXCEPT;
extern void (*glResumeTransformFeedback)() MYGL_NOEXCEPT;
extern void (*glSampleCoverage)(float value, bool invert) MYGL_NOEXCEPT;
extern void (*glSampleMaski)(unsigned int maskNumber, GLbitfield mask) MYGL_NOEXCEPT;
extern void (*glSamplerParameterIiv)(sampler sampler, GLenum pname, const int * param) MYGL_NOEXCEPT;
extern void (*glSamplerParameterIuiv)(sampler sampler, GLenum pname, const unsigned int * param) MYGL_NOEXCEPT;
extern void (*glSamplerParameterf)(sampler sampler, GLenum pname, float param) MYGL_NOEXCEPT;
extern void (*glSamplerParameterfv)(sampler sampler, GLenum pname, const float * param) MYGL_NOEXCEPT;
extern void (*glSamplerParameteri)(sampler sampler, GLenum pname, int param) MYGL_NOEXCEPT;
extern void (*glSamplerParameteriv)(sampler sampler, GLenum pname, const int * param) MYGL_NOEXCEPT;
extern void (*glScissor)(int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glScissorArrayv)(unsigned int first, int count, const int * v) MYGL_NOEXCEPT;
extern void (*glScissorIndexed)(unsigned int index, int left, int bottom, int width, int height) MYGL_NOEXCEPT;
extern void (*glScissorIndexedv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glSecondaryColorFormatNV)(int size, GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glSecondaryColorP3ui)(GLenum type, unsigned int color) MYGL_NOEXCEPT;
extern void (*glSecondaryColorP3uiv)(GLenum type, const unsigned int * color) MYGL_NOEXCEPT;
extern void (*glShaderBinary)(int count, const shader * shaders, GLenum binaryformat, const void * binary, int length) MYGL_NOEXCEPT;
extern void (*glShaderSource)(shader shader, int count, const char *const* string, const int * length) MYGL_NOEXCEPT;
extern void (*glShaderStorageBlockBinding)(shader_program program, unsigned int storageBlockIndex, unsigned int storageBlockBinding) MYGL_NOEXCEPT;
extern void (*glSpecializeShader)(shader shader, const char * pEntryPoint, unsigned int numSpecializationConstants, const unsigned int * pConstantIndex, const unsigned int * pConstantValue) MYGL_NOEXCEPT;
extern void (*glStateCaptureNV)(state state, GLenum mode) MYGL_NOEXCEPT;
extern void (*glStencilFillPathInstancedNV)(int numPaths, GLenum pathNameType, const void * paths, path pathBase, GLenum fillMode, unsigned int mask, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glStencilFillPathNV)(path path, GLenum fillMode, unsigned int mask) MYGL_NOEXCEPT;
extern void (*glStencilFunc)(GLenum func, int ref, unsigned int mask) MYGL_NOEXCEPT;
extern void (*glStencilFuncSeparate)(GLenum face, GLenum func, int ref, unsigned int mask) MYGL_NOEXCEPT;
extern void (*glStencilMask)(unsigned int mask) MYGL_NOEXCEPT;
extern void (*glStencilMaskSeparate)(GLenum face, unsigned int mask) MYGL_NOEXCEPT;
extern void (*glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass) MYGL_NOEXCEPT;
extern void (*glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) MYGL_NOEXCEPT;
extern void (*glStencilStrokePathInstancedNV)(int numPaths, GLenum pathNameType, const void * paths, path pathBase, int reference, unsigned int mask, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glStencilStrokePathNV)(path path, int reference, unsigned int mask) MYGL_NOEXCEPT;
extern void (*glStencilThenCoverFillPathInstancedNV)(int numPaths, GLenum pathNameType, const void * paths, path pathBase, GLenum fillMode, unsigned int mask, GLenum coverMode, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glStencilThenCoverFillPathNV)(path path, GLenum fillMode, unsigned int mask, GLenum coverMode) MYGL_NOEXCEPT;
extern void (*glStencilThenCoverStrokePathInstancedNV)(int numPaths, GLenum pathNameType, const void * paths, path pathBase, int reference, unsigned int mask, GLenum coverMode, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glStencilThenCoverStrokePathNV)(path path, int reference, unsigned int mask, GLenum coverMode) MYGL_NOEXCEPT;
extern void (*glTexBuffer)(GLenum target, GLenum internalformat, buffer buffer) MYGL_NOEXCEPT;
extern void (*glTexBufferRange)(GLenum target, GLenum internalformat, buffer buffer, ptrdiff_t offset, ptrdiff_t size) MYGL_NOEXCEPT;
extern void (*glTexCoordFormatNV)(int size, GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glTexCoordP1ui)(GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP1uiv)(GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP2ui)(GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP2uiv)(GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP3ui)(GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP3uiv)(GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP4ui)(GLenum type, unsigned int coords) MYGL_NOEXCEPT;
extern void (*glTexCoordP4uiv)(GLenum type, const unsigned int * coords) MYGL_NOEXCEPT;
extern void (*glTexImage1D)(GLenum target, int level, int internalformat, int width, int border, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTexImage2D)(GLenum target, int level, int internalformat, int width, int height, int border, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTexImage2DMultisample)(GLenum target, int samples, GLenum internalformat, int width, int height, bool fixedsamplelocations) MYGL_NOEXCEPT;
extern void (*glTexImage3D)(GLenum target, int level, int internalformat, int width, int height, int depth, int border, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTexImage3DMultisample)(GLenum target, int samples, GLenum internalformat, int width, int height, int depth, bool fixedsamplelocations) MYGL_NOEXCEPT;
extern void (*glTexParameterIiv)(GLenum target, GLenum pname, const int * params) MYGL_NOEXCEPT;
extern void (*glTexParameterIuiv)(GLenum target, GLenum pname, const unsigned int * params) MYGL_NOEXCEPT;
extern void (*glTexParameterf)(GLenum target, GLenum pname, float param) MYGL_NOEXCEPT;
extern void (*glTexParameterfv)(GLenum target, GLenum pname, const float * params) MYGL_NOEXCEPT;
extern void (*glTexParameteri)(GLenum target, GLenum pname, int param) MYGL_NOEXCEPT;
extern void (*glTexParameteriv)(GLenum target, GLenum pname, const int * params) MYGL_NOEXCEPT;
extern void (*glTexStorage1D)(GLenum target, int levels, GLenum internalformat, int width) MYGL_NOEXCEPT;
extern void (*glTexStorage2D)(GLenum target, int levels, GLenum internalformat, int width, int height) MYGL_NOEXCEPT;
extern void (*glTexStorage2DMultisample)(GLenum target, int samples, GLenum internalformat, int width, int height, bool fixedsamplelocations) MYGL_NOEXCEPT;
extern void (*glTexStorage3D)(GLenum target, int levels, GLenum internalformat, int width, int height, int depth) MYGL_NOEXCEPT;
extern void (*glTexStorage3DMultisample)(GLenum target, int samples, GLenum internalformat, int width, int height, int depth, bool fixedsamplelocations) MYGL_NOEXCEPT;
extern void (*glTexSubImage1D)(GLenum target, int level, int xoffset, int width, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTexSubImage2D)(GLenum target, int level, int xoffset, int yoffset, int width, int height, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTexSubImage3D)(GLenum target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTextureBarrier)() MYGL_NOEXCEPT;
extern void (*glTextureBuffer)(texture texture, GLenum internalformat, buffer buffer) MYGL_NOEXCEPT;
extern void (*glTextureBufferRange)(texture texture, GLenum internalformat, buffer buffer, ptrdiff_t offset, ptrdiff_t size) MYGL_NOEXCEPT;
extern void (*glTextureParameterIiv)(texture texture, GLenum pname, const int * params) MYGL_NOEXCEPT;
extern void (*glTextureParameterIuiv)(texture texture, GLenum pname, const unsigned int * params) MYGL_NOEXCEPT;
extern void (*glTextureParameterf)(texture texture, GLenum pname, float param) MYGL_NOEXCEPT;
extern void (*glTextureParameterfv)(texture texture, GLenum pname, const float * param) MYGL_NOEXCEPT;
extern void (*glTextureParameteri)(texture texture, GLenum pname, int param) MYGL_NOEXCEPT;
extern void (*glTextureParameteriv)(texture texture, GLenum pname, const int * param) MYGL_NOEXCEPT;
extern void (*glTextureStorage1D)(texture texture, int levels, GLenum internalformat, int width) MYGL_NOEXCEPT;
extern void (*glTextureStorage2D)(texture texture, int levels, GLenum internalformat, int width, int height) MYGL_NOEXCEPT;
extern void (*glTextureStorage2DMultisample)(texture texture, int samples, GLenum internalformat, int width, int height, bool fixedsamplelocations) MYGL_NOEXCEPT;
extern void (*glTextureStorage3D)(texture texture, int levels, GLenum internalformat, int width, int height, int depth) MYGL_NOEXCEPT;
extern void (*glTextureStorage3DMultisample)(texture texture, int samples, GLenum internalformat, int width, int height, int depth, bool fixedsamplelocations) MYGL_NOEXCEPT;
extern void (*glTextureSubImage1D)(texture texture, int level, int xoffset, int width, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTextureSubImage2D)(texture texture, int level, int xoffset, int yoffset, int width, int height, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTextureSubImage3D)(texture texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, GLenum format, GLenum type, const void * pixels) MYGL_NOEXCEPT;
extern void (*glTextureView)(texture texture, GLenum target, unsigned int origtexture, GLenum internalformat, unsigned int minlevel, unsigned int numlevels, unsigned int minlayer, unsigned int numlayers) MYGL_NOEXCEPT;
extern void (*glTransformFeedbackBufferBase)(transform_feedback xfb, unsigned int index, buffer buffer) MYGL_NOEXCEPT;
extern void (*glTransformFeedbackBufferRange)(transform_feedback xfb, unsigned int index, buffer buffer, ptrdiff_t offset, ptrdiff_t size) MYGL_NOEXCEPT;
extern void (*glTransformFeedbackVaryings)(shader_program program, int count, const char *const* varyings, GLenum bufferMode) MYGL_NOEXCEPT;
extern void (*glTransformPathNV)(path resultPath, path srcPath, GLenum transformType, const float * transformValues) MYGL_NOEXCEPT;
extern void (*glUniform1d)(int location, double x) MYGL_NOEXCEPT;
extern void (*glUniform1dv)(int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glUniform1f)(int location, float v0) MYGL_NOEXCEPT;
extern void (*glUniform1fv)(int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glUniform1i)(int location, int v0) MYGL_NOEXCEPT;
extern void (*glUniform1i64ARB)(int location, int64_t x) MYGL_NOEXCEPT;
extern void (*glUniform1i64NV)(int location, int64_t x) MYGL_NOEXCEPT;
extern void (*glUniform1i64vARB)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform1i64vNV)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform1iv)(int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glUniform1ui)(int location, unsigned int v0) MYGL_NOEXCEPT;
extern void (*glUniform1ui64ARB)(int location, uint64_t x) MYGL_NOEXCEPT;
extern void (*glUniform1ui64NV)(int location, uint64_t x) MYGL_NOEXCEPT;
extern void (*glUniform1ui64vARB)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform1ui64vNV)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform1uiv)(int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glUniform2d)(int location, double x, double y) MYGL_NOEXCEPT;
extern void (*glUniform2dv)(int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glUniform2f)(int location, float v0, float v1) MYGL_NOEXCEPT;
extern void (*glUniform2fv)(int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glUniform2i)(int location, int v0, int v1) MYGL_NOEXCEPT;
extern void (*glUniform2i64ARB)(int location, int64_t x, int64_t y) MYGL_NOEXCEPT;
extern void (*glUniform2i64NV)(int location, int64_t x, int64_t y) MYGL_NOEXCEPT;
extern void (*glUniform2i64vARB)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform2i64vNV)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform2iv)(int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glUniform2ui)(int location, unsigned int v0, unsigned int v1) MYGL_NOEXCEPT;
extern void (*glUniform2ui64ARB)(int location, uint64_t x, uint64_t y) MYGL_NOEXCEPT;
extern void (*glUniform2ui64NV)(int location, uint64_t x, uint64_t y) MYGL_NOEXCEPT;
extern void (*glUniform2ui64vARB)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform2ui64vNV)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform2uiv)(int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glUniform3d)(int location, double x, double y, double z) MYGL_NOEXCEPT;
extern void (*glUniform3dv)(int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glUniform3f)(int location, float v0, float v1, float v2) MYGL_NOEXCEPT;
extern void (*glUniform3fv)(int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glUniform3i)(int location, int v0, int v1, int v2) MYGL_NOEXCEPT;
extern void (*glUniform3i64ARB)(int location, int64_t x, int64_t y, int64_t z) MYGL_NOEXCEPT;
extern void (*glUniform3i64NV)(int location, int64_t x, int64_t y, int64_t z) MYGL_NOEXCEPT;
extern void (*glUniform3i64vARB)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform3i64vNV)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform3iv)(int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glUniform3ui)(int location, unsigned int v0, unsigned int v1, unsigned int v2) MYGL_NOEXCEPT;
extern void (*glUniform3ui64ARB)(int location, uint64_t x, uint64_t y, uint64_t z) MYGL_NOEXCEPT;
extern void (*glUniform3ui64NV)(int location, uint64_t x, uint64_t y, uint64_t z) MYGL_NOEXCEPT;
extern void (*glUniform3ui64vARB)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform3ui64vNV)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform3uiv)(int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glUniform4d)(int location, double x, double y, double z, double w) MYGL_NOEXCEPT;
extern void (*glUniform4dv)(int location, int count, const double * value) MYGL_NOEXCEPT;
extern void (*glUniform4f)(int location, float v0, float v1, float v2, float v3) MYGL_NOEXCEPT;
extern void (*glUniform4fv)(int location, int count, const float * value) MYGL_NOEXCEPT;
extern void (*glUniform4i)(int location, int v0, int v1, int v2, int v3) MYGL_NOEXCEPT;
extern void (*glUniform4i64ARB)(int location, int64_t x, int64_t y, int64_t z, int64_t w) MYGL_NOEXCEPT;
extern void (*glUniform4i64NV)(int location, int64_t x, int64_t y, int64_t z, int64_t w) MYGL_NOEXCEPT;
extern void (*glUniform4i64vARB)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform4i64vNV)(int location, int count, const int64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform4iv)(int location, int count, const int * value) MYGL_NOEXCEPT;
extern void (*glUniform4ui)(int location, unsigned int v0, unsigned int v1, unsigned int v2, unsigned int v3) MYGL_NOEXCEPT;
extern void (*glUniform4ui64ARB)(int location, uint64_t x, uint64_t y, uint64_t z, uint64_t w) MYGL_NOEXCEPT;
extern void (*glUniform4ui64NV)(int location, uint64_t x, uint64_t y, uint64_t z, uint64_t w) MYGL_NOEXCEPT;
extern void (*glUniform4ui64vARB)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform4ui64vNV)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniform4uiv)(int location, int count, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glUniformBlockBinding)(shader_program program, unsigned int uniformBlockIndex, unsigned int uniformBlockBinding) MYGL_NOEXCEPT;
extern void (*glUniformHandleui64ARB)(int location, uint64_t value) MYGL_NOEXCEPT;
extern void (*glUniformHandleui64vARB)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix2dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix2fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix2x3dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix2x3fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix2x4dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix2x4fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix3dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix3fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix3x2dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix3x2fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix3x4dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix3x4fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix4dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix4fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix4x2dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix4x2fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix4x3dv)(int location, int count, bool transpose, const double * value) MYGL_NOEXCEPT;
extern void (*glUniformMatrix4x3fv)(int location, int count, bool transpose, const float * value) MYGL_NOEXCEPT;
extern void (*glUniformSubroutinesuiv)(GLenum shadertype, int count, const unsigned int * indices) MYGL_NOEXCEPT;
extern void (*glUniformui64NV)(int location, uint64_t value) MYGL_NOEXCEPT;
extern void (*glUniformui64vNV)(int location, int count, const uint64_t * value) MYGL_NOEXCEPT;
extern bool(*glUnmapBuffer)(GLenum target) MYGL_NOEXCEPT;
extern bool(*glUnmapNamedBuffer)(buffer buffer) MYGL_NOEXCEPT;
extern void (*glUseProgram)(shader_program program) MYGL_NOEXCEPT;
extern void (*glUseProgramStages)(pipeline pipeline, GLbitfield stages, shader_program program) MYGL_NOEXCEPT;
extern void (*glValidateProgram)(shader_program program) MYGL_NOEXCEPT;
extern void (*glValidateProgramPipeline)(pipeline pipeline) MYGL_NOEXCEPT;
extern void (*glVertexArrayAttribBinding)(vertex_array vaobj, unsigned int attribindex, unsigned int bindingindex) MYGL_NOEXCEPT;
extern void (*glVertexArrayAttribFormat)(vertex_array vaobj, unsigned int attribindex, int size, GLenum type, bool normalized, unsigned int relativeoffset) MYGL_NOEXCEPT;
extern void (*glVertexArrayAttribIFormat)(vertex_array vaobj, unsigned int attribindex, int size, GLenum type, unsigned int relativeoffset) MYGL_NOEXCEPT;
extern void (*glVertexArrayAttribLFormat)(vertex_array vaobj, unsigned int attribindex, int size, GLenum type, unsigned int relativeoffset) MYGL_NOEXCEPT;
extern void (*glVertexArrayBindingDivisor)(vertex_array vaobj, unsigned int bindingindex, unsigned int divisor) MYGL_NOEXCEPT;
extern void (*glVertexArrayElementBuffer)(vertex_array vaobj, buffer buffer) MYGL_NOEXCEPT;
extern void (*glVertexArrayVertexBuffer)(vertex_array vaobj, unsigned int bindingindex, buffer buffer, ptrdiff_t offset, int stride) MYGL_NOEXCEPT;
extern void (*glVertexArrayVertexBuffers)(vertex_array vaobj, unsigned int first, int count, const buffer * buffers, const ptrdiff_t * offsets, const int * strides) MYGL_NOEXCEPT;
extern void (*glVertexAttrib1d)(unsigned int index, double x) MYGL_NOEXCEPT;
extern void (*glVertexAttrib1dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib1f)(unsigned int index, float x) MYGL_NOEXCEPT;
extern void (*glVertexAttrib1fv)(unsigned int index, const float * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib1s)(unsigned int index, short x) MYGL_NOEXCEPT;
extern void (*glVertexAttrib1sv)(unsigned int index, const short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib2d)(unsigned int index, double x, double y) MYGL_NOEXCEPT;
extern void (*glVertexAttrib2dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib2f)(unsigned int index, float x, float y) MYGL_NOEXCEPT;
extern void (*glVertexAttrib2fv)(unsigned int index, const float * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib2s)(unsigned int index, short x, short y) MYGL_NOEXCEPT;
extern void (*glVertexAttrib2sv)(unsigned int index, const short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib3d)(unsigned int index, double x, double y, double z) MYGL_NOEXCEPT;
extern void (*glVertexAttrib3dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib3f)(unsigned int index, float x, float y, float z) MYGL_NOEXCEPT;
extern void (*glVertexAttrib3fv)(unsigned int index, const float * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib3s)(unsigned int index, short x, short y, short z) MYGL_NOEXCEPT;
extern void (*glVertexAttrib3sv)(unsigned int index, const short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Nbv)(unsigned int index, const signed char * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Niv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Nsv)(unsigned int index, const short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Nub)(unsigned int index, unsigned char x, unsigned char y, unsigned char z, unsigned char w) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Nubv)(unsigned int index, const unsigned char * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Nuiv)(unsigned int index, const unsigned int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4Nusv)(unsigned int index, const unsigned short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4bv)(unsigned int index, const signed char * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4d)(unsigned int index, double x, double y, double z, double w) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4f)(unsigned int index, float x, float y, float z, float w) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4fv)(unsigned int index, const float * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4iv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4s)(unsigned int index, short x, short y, short z, short w) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4sv)(unsigned int index, const short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4ubv)(unsigned int index, const unsigned char * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4uiv)(unsigned int index, const unsigned int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttrib4usv)(unsigned int index, const unsigned short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribBinding)(unsigned int attribindex, unsigned int bindingindex) MYGL_NOEXCEPT;
extern void (*glVertexAttribDivisor)(unsigned int index, unsigned int divisor) MYGL_NOEXCEPT;
extern void (*glVertexAttribFormat)(unsigned int attribindex, int size, GLenum type, bool normalized, unsigned int relativeoffset) MYGL_NOEXCEPT;
extern void (*glVertexAttribFormatNV)(unsigned int index, int size, GLenum type, bool normalized, int stride) MYGL_NOEXCEPT;
extern void (*glVertexAttribI1i)(unsigned int index, int x) MYGL_NOEXCEPT;
extern void (*glVertexAttribI1iv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI1ui)(unsigned int index, unsigned int x) MYGL_NOEXCEPT;
extern void (*glVertexAttribI1uiv)(unsigned int index, const unsigned int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI2i)(unsigned int index, int x, int y) MYGL_NOEXCEPT;
extern void (*glVertexAttribI2iv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI2ui)(unsigned int index, unsigned int x, unsigned int y) MYGL_NOEXCEPT;
extern void (*glVertexAttribI2uiv)(unsigned int index, const unsigned int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI3i)(unsigned int index, int x, int y, int z) MYGL_NOEXCEPT;
extern void (*glVertexAttribI3iv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI3ui)(unsigned int index, unsigned int x, unsigned int y, unsigned int z) MYGL_NOEXCEPT;
extern void (*glVertexAttribI3uiv)(unsigned int index, const unsigned int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4bv)(unsigned int index, const signed char * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4i)(unsigned int index, int x, int y, int z, int w) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4iv)(unsigned int index, const int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4sv)(unsigned int index, const short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4ubv)(unsigned int index, const unsigned char * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4ui)(unsigned int index, unsigned int x, unsigned int y, unsigned int z, unsigned int w) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4uiv)(unsigned int index, const unsigned int * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribI4usv)(unsigned int index, const unsigned short * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribIFormat)(unsigned int attribindex, int size, GLenum type, unsigned int relativeoffset) MYGL_NOEXCEPT;
extern void (*glVertexAttribIFormatNV)(unsigned int index, int size, GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glVertexAttribIPointer)(unsigned int index, int size, GLenum type, int stride, const void * pointer) MYGL_NOEXCEPT;
extern void (*glVertexAttribL1d)(unsigned int index, double x) MYGL_NOEXCEPT;
extern void (*glVertexAttribL1dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribL1ui64ARB)(unsigned int index, uint64_t x) MYGL_NOEXCEPT;
extern void (*glVertexAttribL1ui64vARB)(unsigned int index, const uint64_t * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribL2d)(unsigned int index, double x, double y) MYGL_NOEXCEPT;
extern void (*glVertexAttribL2dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribL3d)(unsigned int index, double x, double y, double z) MYGL_NOEXCEPT;
extern void (*glVertexAttribL3dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribL4d)(unsigned int index, double x, double y, double z, double w) MYGL_NOEXCEPT;
extern void (*glVertexAttribL4dv)(unsigned int index, const double * v) MYGL_NOEXCEPT;
extern void (*glVertexAttribLFormat)(unsigned int attribindex, int size, GLenum type, unsigned int relativeoffset) MYGL_NOEXCEPT;
extern void (*glVertexAttribLPointer)(unsigned int index, int size, GLenum type, int stride, const void * pointer) MYGL_NOEXCEPT;
extern void (*glVertexAttribP1ui)(unsigned int index, GLenum type, bool normalized, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP1uiv)(unsigned int index, GLenum type, bool normalized, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP2ui)(unsigned int index, GLenum type, bool normalized, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP2uiv)(unsigned int index, GLenum type, bool normalized, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP3ui)(unsigned int index, GLenum type, bool normalized, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP3uiv)(unsigned int index, GLenum type, bool normalized, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP4ui)(unsigned int index, GLenum type, bool normalized, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexAttribP4uiv)(unsigned int index, GLenum type, bool normalized, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glVertexAttribPointer)(unsigned int index, int size, GLenum type, bool normalized, int stride, const void * pointer) MYGL_NOEXCEPT;
extern void (*glVertexBindingDivisor)(unsigned int bindingindex, unsigned int divisor) MYGL_NOEXCEPT;
extern void (*glVertexFormatNV)(int size, GLenum type, int stride) MYGL_NOEXCEPT;
extern void (*glVertexP2ui)(GLenum type, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexP2uiv)(GLenum type, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glVertexP3ui)(GLenum type, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexP3uiv)(GLenum type, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glVertexP4ui)(GLenum type, unsigned int value) MYGL_NOEXCEPT;
extern void (*glVertexP4uiv)(GLenum type, const unsigned int * value) MYGL_NOEXCEPT;
extern void (*glViewport)(int x, int y, int width, int height) MYGL_NOEXCEPT;
extern void (*glViewportArrayv)(unsigned int first, int count, const float * v) MYGL_NOEXCEPT;
extern void (*glViewportIndexedf)(unsigned int index, float x, float y, float w, float h) MYGL_NOEXCEPT;
extern void (*glViewportIndexedfv)(unsigned int index, const float * v) MYGL_NOEXCEPT;
extern void (*glWaitSync)(GLsync sync, GLbitfield flags, uint64_t timeout) MYGL_NOEXCEPT;
extern void (*glWeightPathsNV)(path resultPath, int numPaths, const path * paths, const float * weights) MYGL_NOEXCEPT;

#if defined(MYGL_IMPLEMENTATION)
#include "mygl_functions.inl"
#endif
