string(TOUPPER ${CMAKE_BUILD_TYPE} uppercase_CMAKE_BUILD_TYPE)
if(uppercase_CMAKE_BUILD_TYPE MATCHES "^(DEBUG)$")
    set(LIB_PATH_APPENDIX "dbg")
elseif(uppercase_CMAKE_BUILD_TYPE MATCHES "^(RELEASE|RELWITHDEBINFO|MINSIZEREL)$")
    set(LIB_PATH_APPENDIX "")
else ()
    message(FATAL_ERROR "Invalid value for CMAKE_BUILD_TYPE: ${uppercase_CMAKE_BUILD_TYPE}")
endif()

MACRO(add_ext_lib result filename filepath)
    set(${result} ${filepath}/${filename})
    #message(${filepath} ${filename})
    #find_library(result NAMES ${filename} HINTS ${filepath})
    message("${result}: at " ${${result}})
    list(APPEND LIBRARIES ${${result}})
ENDMACRO()
