MACRO(make_executable result directory)
    file(GLOB_RECURSE SRC_C "${directory}/*.c")
    file(GLOB_RECURSE SRC_CPP "${directory}/*.cpp")
    file(GLOB_RECURSE SRC_H "${directory}/*.h")
    file(GLOB_RECURSE SRC_HPP "${directory}/*.hpp")
    add_executable(${result} ${SRC_C} ${SRC_CPP} ${SRC_H} ${SRC_HPP} "${PROJECT_SOURCE_DIR}/src/res/default_app.rc")
ENDMACRO()