MACRO(make_library result directory list_to_append_to success)	
    file(GLOB_RECURSE SRC_C "${directory}/*.c")
    file(GLOB_RECURSE SRC_CPP "${directory}/*.cpp")
    file(GLOB_RECURSE SRC_CC "${directory}/*.cc")
    file(GLOB_RECURSE SRC_H "${directory}/*.h")
    file(GLOB_RECURSE SRC_HPP "${directory}/*.hpp")
    if(NOT SRC_C AND NOT SRC_CPP AND NOT SRC_CC)
        set(success 0)
    else()
        add_library(${result} ${SRC_C} ${SRC_CPP} ${SRC_CC} ${SRC_H} ${SRC_HPP})
        list(APPEND ${list_to_append_to} ${result})
        set(success 1)
    endif()
ENDMACRO()