file(GLOB_RECURSE gfx_current_vert ${GFX_SORUCE_DIR}/*.vert)
file(GLOB_RECURSE gfx_current_frag ${GFX_SORUCE_DIR}/*.frag)
file(GLOB_RECURSE gfx_current_geom ${GFX_SORUCE_DIR}/*.geom)
file(GLOB_RECURSE gfx_current_tese ${GFX_SORUCE_DIR}/*.tese)
file(GLOB_RECURSE gfx_current_tesc ${GFX_SORUCE_DIR}/*.tesc)
file(GLOB_RECURSE gfx_current_comp ${GFX_SORUCE_DIR}/*.comp)

set(GLSLC_COMMAND glslc)
foreach(file ${gfx_current_frag} ${gfx_current_vert} ${gfx_current_geom} ${gfx_current_tese} ${gfx_current_tesc} ${gfx_current_comp})
	file(RELATIVE_PATH full_relative_file ${GFX_PROJECT_SOURCE_DIR}/ ${file})
	set(tmp_full_relative_file ${full_relative_file})
	string(REGEX REPLACE "[- .\\/]" "_" full_relative_file ${full_relative_file})
	string(TOUPPER ${full_relative_file} full_relative_file)
	set(full_relative_file GFX_SHADER_SOURCE_${full_relative_file})
	
	message("[SPIRV] Compiling ${tmp_full_relative_file} ...")
	execute_process(COMMAND ${GLSLC_COMMAND} -mfmt=c -I ${GLOBAL_SPV_INCLUDE_DIR} "${file}" -o ${GFX_BINARY_DIR}/out.carr)
	if(FILE_ERROR)
		message(FATAL_ERROR ${FILE_ERROR})
	endif()
	file(READ ${GFX_BINARY_DIR}/out.carr ${full_relative_file})
endforeach()

file(WRITE ${GFX_BINARY_DIR}/spv.lock "locked!")
configure_file(${GFX_IN} ${GFX_OUT} @ONLY)
message(${GFX_OUT})